### ISSUE TITLE
Working in simulator & TestFlight, but not during ionic cordova run

### ISSUE THREAD

**Issue by patrickchoi** [samkelleher/cordova-plugin-applepay#38] opened 2018-09-05 05:34 UTC
I cannot get the Apple Pay window to open when using "ionic cordova run ios". 

Surprisingly it works in the simulator (dummy card) and TestFlight (real card!). 

My device is configured with an iTunes sandbox account. Does the plugin not work with that?

**Comment by ajcrites** [comment] 2018-12-21 14:04
Closing as a duplicate of #34 and possibly #31

**Closed by ajcrites** 2018-12-21 14:04 UTC
